title: An Artificial Intelligence and Machine Learning Blog
name: An AI and ML Blog
email: aarn.wong@example.com
description: A blog about artificial intelligence and machine learning.
meta_description: Blogging about artificial intelligence and machine learning
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://blog.aaronccwong.com' # the base hostname & protocol for your site, e.g. http://example.com
github_username:  AaronCCWong

author:
  twitter: aar_wong
  name: Aaron Wong

domain_name: 'https://blog.aaronccwong.com'
google_analytics: 'UA-70347604-3'
disqus: true
disqus_shortname: 'an-ai-and-ml-blog'

# Build settings
markdown: kramdown
theme: minima
plugins: [jekyll-paginate, jekyll-seo-tag]
paginate: 20

aboutPage: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:year/:title/
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

twitter:
    username: aar_wong
    card: summary

social:
  name: Aaron Wong
  links:
    - https://twitter.com/aar_wong
    - https://www.linkedin.com/in/aaron-wong-92041342/
    - https://github.com/AaronCCWong
